SYMBOLS_YAML = """# Gruvbox-inspired symbols
SYMBOLS:
  checkmark: "✔"
  cross: "✘"
  dot: "•"
  caret: "^"
  space: " "
  pipe: "|"
  slash: "/"
  parenthesis_left: "("
  parenthesis_right: ")"
  bracket_left: "["
  bracket_right: "]"
  colon: ":"
  percentage: "%"
  snowflake: "❋"
  filled_square: "■"
  empty_square: "□"
"""
