SYMBOLS_YAML = """# Gruvbox-inspired symbols
SYMBOLS:
  space: " "
  parenthesis_left: "("
  parenthesis_right: ")"
  bracket_left: "["
  bracket_right: "]"
  pipe: "|"
  slash: "/"
  colon: ":"
  percentage: "%"
  caret: "^"
  checkmark: "✔"
  cross: "✘"
  dot: "•"
  bullseye: "⦾"
  star: "★"
  filled_square: "■"
  empty_square: "□"
"""
