POSSIBLE_LANG_SLUGS = ["cpp", "java", "python", "python3", "c", "csharp", "javascript", "typescript", "php", "swift", "kotlin", "dart", "golang", "ruby", "scala", "rust", "racket", "erlang", "elixir"]

POSSIBLE_FILE_EXTENSIONS = ["cpp", "java", "py", "py3", "c", "cs", "js", "ts", "php", "swift", "kt", "dart", "go", "rb", "scala", "rs", "rkt", "erl", "ex"]

EXTENSION_TO_LANG_SLUG = {
    "cpp": "cpp",
    "java": "java",
    "py": "python",
    "py3": "python3",
    "c": "c",
    "cs": "csharp",
    "js": "javascript",
    "ts": "typescript",
    "php": "php",
    "swift": "swift",
    "kt": "kotlin",
    "dart": "dart",
    "go": "golang",
    "rb": "ruby",
    "scala": "scala",
    "rs": "rust",
    "rkt": "racket",
    "erl": "erlang",
    "ex": "elixir"
}

LANG_SLUG_TO_EXTENSION = {
    "cpp": "cpp",
    "java": "java",
    "python": "py",
    "python3": "py3",
    "c": "c",
    "csharp": "cs",
    "javascript": "js",
    "typescript": "ts",
    "php": "php",
    "swift": "swift",
    "kotlin": "kt",
    "dart": "dart",
    "golang": "go",
    "ruby": "rb",
    "scala": "scala",
    "rust": "rs",
    "racket": "rkt",
    "erlang": "erl",
    "elixir": "ex"
}

POSSIBLE_TAGS = [
    "array",
    "string",
    "hash-table",
    "dynamic-programming",
    "math",
    "sorting",
    "greedy",
    "depth-first-search",
    "binary-search",
    "database",
    "matrix",
    "tree",
    "breadth-first-search",
    "bit-manipulation",
    "two-pointers",
    "prefix-sum",
    "heap-priority-queue",
    "binary-tree",
    "simulation",
    "stack",
    "counting",
    "graph",
    "sliding-window",
    "design",
    "backtracking",
    "enumeration",
    "union-find",
    "linked-list",
    "ordered-set",
    "number-theory",
    "monotonic-stack",
    "trie",
    "segment-tree",
    "bitmask",
    "queue",
    "divide-and-conquer",
    "recursion",
    "combinatorics",
    "binary-search-tree",
    "hash-function",
    "memoization",
    "binary-indexed-tree",
    "geometry",
    "string-matching",
    "topological-sort",
    "shortest-path",
    "rolling-hash",
    "game-theory",
    "interactive",
    "data-stream",
    "monotonic-queue",
    "brainteaser",
    "randomized",
    "merge-sort",
    "doubly-linked-list",
    "counting-sort",
    "iterator",
    "concurrency",
    "probability-and-statistics",
    "quickselect",
    "suffix-array",
    "bucket-sort",
    "minimum-spanning-tree",
    "shell",
    "line-sweep",
    "reservoir-sampling",
    "strongly-connected-component",
    "eulerian-circuit",
    "radix-sort",
    "rejection-sampling",
    "biconnected-component"
]

